### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'rfft'

### ISSUE THREAD

**Issue by laisimiao** [visionml/pytracking#364]
When I update PyTorch to 1.9.0 and eval atom default, it occurs this error:
`AttributeError: module 'torch' has no attribute 'rfft'` in **fourier.py**, which means function changed its signature using higher version pytorch.
So rather than downgrading pytorch version, how to modify the codes to adapt it to more versions of pytorch?
Here:
https://github.com/visionml/pytracking/blob/47d9c1641eca44137c9c71ed398da91bf301c751/pytracking/libs/fourier.py#L19-L31

**Comment by prexen** [comment]
Use torch.fft.irfft() instead of torch.rfft()
But that is just the beginning of your problems in trying to run pytracking

**Comment by TsingWei** [comment]
> Use torch.fft.irfft() instead of torch.rfft() But that is just the beginning of your problems in trying to run pytracking
Agree.  So much grateful to pytracking but the code of it is out of date.

**Comment by tongxiaozhong14** [comment]
> When I update PyTorch to 1.9.0 and eval atom default, it occurs this error: `AttributeError: module 'torch' has no attribute 'rfft'` in **fourier.py**, which means function changed its signature using higher version pytorch. So rather than downgrading pytorch version, how to modify the codes to adapt it to more versions of pytorch? Here:
> 
> https://github.com/visionml/pytracking/blob/47d9c1641eca44137c9c71ed398da91bf301c751/pytracking/libs/fourier.py#L19-L31


@tensor_operation
def cfft2(a):

# """Do FFT and center the low frequency 
#    component.Always produces odd(full)output sizes.
#    """
    return rfftshift2(torch.rfft(a,2))
    # return rfftshift2(rfft(a，2))
    # return rfftshift2(torch.view as real(torch.fft.rfftn(a)))

@tensor_operation
def cifft2(a,signal_sizes=None):
# """Do inverse FFT corresponding to cfft2."""

    # return torch.fft.irfft(irfftshift2(a),2)
    # return torch,fft,irfftn(torch.view_as_complex(irfftshift2(a)),siqnal_sizes)
    return torch,irfft(irfftshift2(a),2,signal_sizes=signal_sizes)

**Comment by tongxiaozhong14** [comment]
> When I update PyTorch to 1.9.0 and eval atom default, it occurs this error: `AttributeError: module 'torch' has no attribute 'rfft'` in **fourier.py**, which means function changed its signature using higher version pytorch. So rather than downgrading pytorch version, how to modify the codes to adapt it to more versions of pytorch? Here:
> 
> https://github.com/visionml/pytracking/blob/47d9c1641eca44137c9c71ed398da91bf301c751/pytracking/libs/fourier.py#L19-L31

```

@tensor_operation
def cfft2(a):

# """Do FFT and center the low frequency 
#    component.Always produces odd(full)output sizes.
#    """
    return rfftshift2(torch.rfft(a,2))
    # return rfftshift2(rfft(a，2))
    # return rfftshift2(torch.view as real(torch.fft.rfftn(a)))

@tensor_operation
def cifft2(a,signal_sizes=None):
# """Do inverse FFT corresponding to cfft2."""

    # return torch.fft.irfft(irfftshift2(a),2)
    # return torch,fft,irfftn(torch.view_as_complex(irfftshift2(a)),siqnal_sizes)
    return torch,irfft(irfftshift2(a),2,signal_sizes=signal_sizes)

```
